### ISSUE TITLE
Basic Memory Issue

### ISSUE THREAD

**Issue by ghost** [8085simulator/8085simulator.github.io#2]
I can't seem to find a way to load a program without having my memory completely reset. 
**In detail**: Lets say I load a program and run it. The program fills some empty space with data. Then, I want to load another program and do something with the data in that space. But when I load the program, memory resets and I've lost the data that the previous program had in.

Is there any way to bypass this, or was it designed to work this way?

**Comment by cyberjupiter** [comment]
Try filling the memory manually after loading second program.
